/**
 * Турските (традиционните) имена на градовете в България – за турския език (етап 10).
 * Само градовете (областните центрове, градовете от календара на Мюфтийството и няколко
 * града с турско население); за останалите места остава латинското изписване.
 * Ключът е българското име.
 */
export const TR_PLACE_NAMES: Readonly<Record<string, string>> = {
  Айтос: 'Aydos',
  Балчик: 'Balçık',
  Благоевград: 'Yukarı Cuma',
  Бургас: 'Burgaz',
  Варна: 'Varna',
  'Велики Преслав': 'Preslav',
  'Велико Търново': 'Tırnova',
  'Гоце Делчев': 'Nevrokop',
  Добрич: 'Dobriç',
  Исперих: 'Kemallar',
  Каолиново: 'Bohçalar',
  Карлово: 'Karlova',
  Карнобат: 'Karinabad',
  Котел: 'Kazan',
  Крумовград: 'Koşukavak',
  Кубрат: 'Balbunar',
  Кърджали: 'Kırcaali',
  Ловеч: 'Lofça',
  Никопол: 'Niğbolu',
  'Нова Загора': 'Yeni Zağra',
  'Нови пазар': 'Yeni Pazar',
  Пазарджик: 'Pazarcık',
  Плевен: 'Plevne',
  Пловдив: 'Filibe',
  Провадия: 'Pravadi',
  Разград: 'Hezargrad',
  Русе: 'Rusçuk',
  Свищов: 'Ziştovi',
  Силистра: 'Silistre',
  Сливен: 'İslimiye',
  Смолян: 'Paşmaklı',
  София: 'Sofya',
  'Стара Загора': 'Eski Zağra',
  Търговище: 'Eski Cuma',
  Харманли: 'Harmanlı',
  Хасково: 'Hasköy',
  Шумен: 'Şumnu',
  Ямбол: 'Yanbolu',
  Видин: 'Vidin',
  Враца: 'İvraca',
  Габрово: 'Gabrova',
  Кюстендил: 'Köstendil',
  Момчилград: 'Mestanlı',
  Джебел: 'Cebel',
  Ардино: 'Eğridere',
  Омуртаг: 'Osmanpazarı',
  Тутракан: 'Turtokan',
  Дулово: 'Akkadınlar',
};
